[phases.setup]
nixPkgs = ["bun"]

[phases.install]
cmds = ["cd packages/web && bun install"]

[phases.build]
cmds = ["cd packages/web && bun run build"]

[start]
cmd = "cd packages/web && bun server.ts"
